const db=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);let content=null;
const $=id=>document.getElementById(id);
async function boot(){const {data:{session}}=await db.auth.getSession();if(session){showEditor();load()}else $("loginPanel").classList.remove("hidden")}
function showEditor(){$("loginPanel").classList.add("hidden");$("editor").classList.remove("hidden")}
$("login").onclick=async()=>{let {error}=await db.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error)$("loginMsg").textContent=error.message;else{showEditor();load()}};
$("logout").onclick=()=>db.auth.signOut().then(()=>location.reload());
async function load(){let {data,error}=await db.from("site_content").select("content").eq("id",1).single();if(error){$("saveMsg").textContent=error.message;return}content=data.content;fill(content)}
function fill(c){$("heroSummary").value=c.heroSummary;$("aboutTitle").value=c.aboutTitle;$("about1").value=c.about1;$("about2").value=c.about2;$("currentRole").value=c.currentRole;$("industry").value=c.industry;$("location").value=c.location;$("languages").value=c.languages;c.stats.forEach((x,i)=>{$("stat"+(i+1)).value=x[0];$("stat"+(i+1)+"l").value=x[1]});$("experienceJson").value=JSON.stringify(c.experience,null,2);$("expertiseTitle").value=c.expertiseTitle;$("skills").value=c.skills.join("\n");$("expertiseJson").value=JSON.stringify(c.expertise,null,2);$("educationJson").value=JSON.stringify(c.education,null,2);$("contactTitle").value=c.contactTitle;$("contactIntro").value=c.contactIntro;$("contactEmail").value=c.email;$("contactPhone").value=c.phone;$("whatsapp").value=c.whatsapp;$("linkedin").value=c.linkedin}
$("save").onclick=async()=>{try{let c={...content,heroSummary:$("heroSummary").value,aboutTitle:$("aboutTitle").value,about1:$("about1").value,about2:$("about2").value,currentRole:$("currentRole").value,industry:$("industry").value,location:$("location").value,languages:$("languages").value,stats:[1,2,3,4].map(i=>[$("stat"+i).value,$("stat"+i+"l").value]),experience:JSON.parse($("experienceJson").value),expertiseTitle:$("expertiseTitle").value,skills:$("skills").value.split("\n").map(x=>x.trim()).filter(Boolean),expertise:JSON.parse($("expertiseJson").value),education:JSON.parse($("educationJson").value),contactTitle:$("contactTitle").value,contactIntro:$("contactIntro").value,email:$("contactEmail").value,phone:$("contactPhone").value,whatsapp:$("whatsapp").value,linkedin:$("linkedin").value};let {error}=await db.from("site_content").update({content:c,updated_at:new Date().toISOString()}).eq("id",1);if(error)throw error;content=c;$("saveMsg").textContent="Saved — website updated.";setTimeout(()=>$("saveMsg").textContent="",2500)}catch(e){$("saveMsg").textContent="Error: "+e.message}};
$("uploadPhoto").onclick=async()=>{let f=$("photo").files[0];if(!f)return $("photoMsg").textContent="Choose a photo first.";let ext=f.name.split(".").pop().toLowerCase();let path="profile."+ext;let {error}=await db.storage.from("site-assets").upload(path,f,{upsert:true,contentType:f.type});if(error)return $("photoMsg").textContent=error.message;let {data}=db.storage.from("site-assets").getPublicUrl(path);let {error:e2}=await db.from("site_content").update({photo_url:data.publicUrl,updated_at:new Date().toISOString()}).eq("id",1);$("photoMsg").textContent=e2?e2.message:"Photo uploaded. Add photo_url rendering if you want storage photo to replace the default.";};
boot();